//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 16.0.32413.511
// 
namespace ClientOfProject.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlavorsIiceCream", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class FlavorsIiceCream : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int CodeIceCreamField;
        
        private bool IsMilkField;
        
        private string NameIceCreamField;
        
        private string PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeIceCream {
            get {
                return this.CodeIceCreamField;
            }
            set {
                if ((this.CodeIceCreamField.Equals(value) != true)) {
                    this.CodeIceCreamField = value;
                    this.RaisePropertyChanged("CodeIceCream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMilk {
            get {
                return this.IsMilkField;
            }
            set {
                if ((this.IsMilkField.Equals(value) != true)) {
                    this.IsMilkField = value;
                    this.RaisePropertyChanged("IsMilk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameIceCream {
            get {
                return this.NameIceCreamField;
            }
            set {
                if ((object.ReferenceEquals(this.NameIceCreamField, value) != true)) {
                    this.NameIceCreamField = value;
                    this.RaisePropertyChanged("NameIceCream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.SpecialDessert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.AdditionAccordingCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.Additions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.SpecificationAdditionsDessert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.DetailingDessertInPurchase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.Purchases))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.Clients))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.ConstantConstricted))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.DsetailingScoopOfIceCreamDessert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.ConstrictedIinPurchase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientOfProject.ServiceReference1.FlavorsIiceCream))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialDessert", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class SpecialDessert : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int AmountAdditionsField;
        
        private int AmountIceCreamField;
        
        private ClientOfProject.ServiceReference1.Category CodeCategoryField;
        
        private int CodeDessertField;
        
        private string DescriptionField;
        
        private string NameDessertField;
        
        private string PictureField;
        
        private int PriceField;
        
        private string SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountAdditions {
            get {
                return this.AmountAdditionsField;
            }
            set {
                if ((this.AmountAdditionsField.Equals(value) != true)) {
                    this.AmountAdditionsField = value;
                    this.RaisePropertyChanged("AmountAdditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountIceCream {
            get {
                return this.AmountIceCreamField;
            }
            set {
                if ((this.AmountIceCreamField.Equals(value) != true)) {
                    this.AmountIceCreamField = value;
                    this.RaisePropertyChanged("AmountIceCream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Category CodeCategory {
            get {
                return this.CodeCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeCategoryField, value) != true)) {
                    this.CodeCategoryField = value;
                    this.RaisePropertyChanged("CodeCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeDessert {
            get {
                return this.CodeDessertField;
            }
            set {
                if ((this.CodeDessertField.Equals(value) != true)) {
                    this.CodeDessertField = value;
                    this.RaisePropertyChanged("CodeDessert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameDessert {
            get {
                return this.NameDessertField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDessertField, value) != true)) {
                    this.NameDessertField = value;
                    this.RaisePropertyChanged("NameDessert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Category : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int CodeCategoryField;
        
        private string NameCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeCategory {
            get {
                return this.CodeCategoryField;
            }
            set {
                if ((this.CodeCategoryField.Equals(value) != true)) {
                    this.CodeCategoryField = value;
                    this.RaisePropertyChanged("CodeCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCategory {
            get {
                return this.NameCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.NameCategoryField, value) != true)) {
                    this.NameCategoryField = value;
                    this.RaisePropertyChanged("NameCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionAccordingCategory", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class AdditionAccordingCategory : ClientOfProject.ServiceReference1.BaseEntity {
        
        private ClientOfProject.ServiceReference1.Additions CodeAdditionField;
        
        private ClientOfProject.ServiceReference1.Category CodeCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Additions CodeAddition {
            get {
                return this.CodeAdditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeAdditionField, value) != true)) {
                    this.CodeAdditionField = value;
                    this.RaisePropertyChanged("CodeAddition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Category CodeCategory {
            get {
                return this.CodeCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeCategoryField, value) != true)) {
                    this.CodeCategoryField = value;
                    this.RaisePropertyChanged("CodeCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Additions", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Additions : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int CodeAdditionField;
        
        private string NameAdditionField;
        
        private string PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeAddition {
            get {
                return this.CodeAdditionField;
            }
            set {
                if ((this.CodeAdditionField.Equals(value) != true)) {
                    this.CodeAdditionField = value;
                    this.RaisePropertyChanged("CodeAddition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAddition {
            get {
                return this.NameAdditionField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAdditionField, value) != true)) {
                    this.NameAdditionField = value;
                    this.RaisePropertyChanged("NameAddition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecificationAdditionsDessert", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class SpecificationAdditionsDessert : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int AmountField;
        
        private ClientOfProject.ServiceReference1.Additions CodeAdditionsField;
        
        private ClientOfProject.ServiceReference1.DetailingDessertInPurchase CodeSpecificationAdditionsDessertField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Additions CodeAdditions {
            get {
                return this.CodeAdditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeAdditionsField, value) != true)) {
                    this.CodeAdditionsField = value;
                    this.RaisePropertyChanged("CodeAdditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.DetailingDessertInPurchase CodeSpecificationAdditionsDessert {
            get {
                return this.CodeSpecificationAdditionsDessertField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSpecificationAdditionsDessertField, value) != true)) {
                    this.CodeSpecificationAdditionsDessertField = value;
                    this.RaisePropertyChanged("CodeSpecificationAdditionsDessert");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailingDessertInPurchase", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class DetailingDessertInPurchase : ClientOfProject.ServiceReference1.BaseEntity {
        
        private ClientOfProject.ServiceReference1.SpecialDessert CodeDessertField;
        
        private ClientOfProject.ServiceReference1.Purchases CodePurchasesField;
        
        private int CodeSpecificationDessertField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.SpecialDessert CodeDessert {
            get {
                return this.CodeDessertField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeDessertField, value) != true)) {
                    this.CodeDessertField = value;
                    this.RaisePropertyChanged("CodeDessert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Purchases CodePurchases {
            get {
                return this.CodePurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePurchasesField, value) != true)) {
                    this.CodePurchasesField = value;
                    this.RaisePropertyChanged("CodePurchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeSpecificationDessert {
            get {
                return this.CodeSpecificationDessertField;
            }
            set {
                if ((this.CodeSpecificationDessertField.Equals(value) != true)) {
                    this.CodeSpecificationDessertField = value;
                    this.RaisePropertyChanged("CodeSpecificationDessert");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchases", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Purchases : ClientOfProject.ServiceReference1.BaseEntity {
        
        private ClientOfProject.ServiceReference1.Clients CodeClientField;
        
        private int CodePurchaseField;
        
        private string DatePurchaseField;
        
        private int FinalPriceField;
        
        private string PaymentMethodField;
        
        private string TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Clients CodeClient {
            get {
                return this.CodeClientField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeClientField, value) != true)) {
                    this.CodeClientField = value;
                    this.RaisePropertyChanged("CodeClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodePurchase {
            get {
                return this.CodePurchaseField;
            }
            set {
                if ((this.CodePurchaseField.Equals(value) != true)) {
                    this.CodePurchaseField = value;
                    this.RaisePropertyChanged("CodePurchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatePurchase {
            get {
                return this.DatePurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DatePurchaseField, value) != true)) {
                    this.DatePurchaseField = value;
                    this.RaisePropertyChanged("DatePurchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalPrice {
            get {
                return this.FinalPriceField;
            }
            set {
                if ((this.FinalPriceField.Equals(value) != true)) {
                    this.FinalPriceField = value;
                    this.RaisePropertyChanged("FinalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clients", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Clients : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int CodeClientField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MailField;
        
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeClient {
            get {
                return this.CodeClientField;
            }
            set {
                if ((this.CodeClientField.Equals(value) != true)) {
                    this.CodeClientField = value;
                    this.RaisePropertyChanged("CodeClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstantConstricted", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class ConstantConstricted : ClientOfProject.ServiceReference1.BaseEntity {
        
        private ClientOfProject.ServiceReference1.Category CodeCategoryField;
        
        private int CodeConstrictedField;
        
        private string NameConstrictedField;
        
        private string PictureField;
        
        private int PriceField;
        
        private string SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Category CodeCategory {
            get {
                return this.CodeCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeCategoryField, value) != true)) {
                    this.CodeCategoryField = value;
                    this.RaisePropertyChanged("CodeCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeConstricted {
            get {
                return this.CodeConstrictedField;
            }
            set {
                if ((this.CodeConstrictedField.Equals(value) != true)) {
                    this.CodeConstrictedField = value;
                    this.RaisePropertyChanged("CodeConstricted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameConstricted {
            get {
                return this.NameConstrictedField;
            }
            set {
                if ((object.ReferenceEquals(this.NameConstrictedField, value) != true)) {
                    this.NameConstrictedField = value;
                    this.RaisePropertyChanged("NameConstricted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DsetailingScoopOfIceCreamDessert", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class DsetailingScoopOfIceCreamDessert : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int AmountField;
        
        private ClientOfProject.ServiceReference1.FlavorsIiceCream CodeIceCreamField;
        
        private ClientOfProject.ServiceReference1.DetailingDessertInPurchase CodeSpecificationDessertField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.FlavorsIiceCream CodeIceCream {
            get {
                return this.CodeIceCreamField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeIceCreamField, value) != true)) {
                    this.CodeIceCreamField = value;
                    this.RaisePropertyChanged("CodeIceCream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.DetailingDessertInPurchase CodeSpecificationDessert {
            get {
                return this.CodeSpecificationDessertField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSpecificationDessertField, value) != true)) {
                    this.CodeSpecificationDessertField = value;
                    this.RaisePropertyChanged("CodeSpecificationDessert");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstrictedIinPurchase", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class ConstrictedIinPurchase : ClientOfProject.ServiceReference1.BaseEntity {
        
        private int AmountField;
        
        private int CodeConstrictedField;
        
        private ClientOfProject.ServiceReference1.Purchases CodePurchaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeConstricted {
            get {
                return this.CodeConstrictedField;
            }
            set {
                if ((this.CodeConstrictedField.Equals(value) != true)) {
                    this.CodeConstrictedField = value;
                    this.RaisePropertyChanged("CodeConstricted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientOfProject.ServiceReference1.Purchases CodePurchase {
            get {
                return this.CodePurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePurchaseField, value) != true)) {
                    this.CodePurchaseField = value;
                    this.RaisePropertyChanged("CodePurchase");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFlavors", ReplyAction="http://tempuri.org/IService1/GetAllFlavorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.FlavorsIiceCream>> GetAllFlavorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecielDessert", ReplyAction="http://tempuri.org/IService1/GetSpecielDessertResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.SpecialDessert>> GetSpecielDessertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAdditions", ReplyAction="http://tempuri.org/IService1/GetAllAdditionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.AdditionAccordingCategory>> GetAllAdditionsAsync(ClientOfProject.ServiceReference1.Category c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdditions", ReplyAction="http://tempuri.org/IService1/GetAdditionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.Additions>> GetAdditionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategory", ReplyAction="http://tempuri.org/IService1/GetAllCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.Category>> GetAllCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecificationAdditionsDesserts", ReplyAction="http://tempuri.org/IService1/GetSpecificationAdditionsDessertsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.SpecificationAdditionsDessert>> GetSpecificationAdditionsDessertsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdditionAccordingCategories", ReplyAction="http://tempuri.org/IService1/GetAdditionAccordingCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.AdditionAccordingCategory>> GetAdditionAccordingCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToAddition", ReplyAction="http://tempuri.org/IService1/GetCodeToAdditionResponse")]
        System.Threading.Tasks.Task<int> GetCodeToAdditionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToFlavors", ReplyAction="http://tempuri.org/IService1/GetCodeToFlavorsResponse")]
        System.Threading.Tasks.Task<int> GetCodeToFlavorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToMutzar", ReplyAction="http://tempuri.org/IService1/GetCodeToMutzarResponse")]
        System.Threading.Tasks.Task<int> GetCodeToMutzarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToClient", ReplyAction="http://tempuri.org/IService1/GetCodeToClientResponse")]
        System.Threading.Tasks.Task<int> GetCodeToClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToDettalingDessert", ReplyAction="http://tempuri.org/IService1/GetCodeToDettalingDessertResponse")]
        System.Threading.Tasks.Task<int> GetCodeToDettalingDessertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAdditionAcordingCategory", ReplyAction="http://tempuri.org/IService1/AddAdditionAcordingCategoryResponse")]
        System.Threading.Tasks.Task AddAdditionAcordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAdition", ReplyAction="http://tempuri.org/IService1/AddAditionResponse")]
        System.Threading.Tasks.Task<int> AddAditionAsync(ClientOfProject.ServiceReference1.Additions a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddClient", ReplyAction="http://tempuri.org/IService1/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(ClientOfProject.ServiceReference1.Clients c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addspecialdessert", ReplyAction="http://tempuri.org/IService1/AddspecialdessertResponse")]
        System.Threading.Tasks.Task<int> AddspecialdessertAsync(ClientOfProject.ServiceReference1.SpecialDessert s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddConstantConstricted", ReplyAction="http://tempuri.org/IService1/AddConstantConstrictedResponse")]
        System.Threading.Tasks.Task<int> AddConstantConstrictedAsync(ClientOfProject.ServiceReference1.ConstantConstricted con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFlavorIceCream", ReplyAction="http://tempuri.org/IService1/AddFlavorIceCreamResponse")]
        System.Threading.Tasks.Task<int> AddFlavorIceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPurches", ReplyAction="http://tempuri.org/IService1/AddPurchesResponse")]
        System.Threading.Tasks.Task<int> AddPurchesAsync(ClientOfProject.ServiceReference1.Purchases pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSpecificationAdditionsDessert", ReplyAction="http://tempuri.org/IService1/AddSpecificationAdditionsDessertResponse")]
        System.Threading.Tasks.Task<int> AddSpecificationAdditionsDessertAsync(ClientOfProject.ServiceReference1.SpecificationAdditionsDessert sad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Adddetailing_scoop_of_ice_cream_dessert", ReplyAction="http://tempuri.org/IService1/Adddetailing_scoop_of_ice_cream_dessertResponse")]
        System.Threading.Tasks.Task<int> Adddetailing_scoop_of_ice_cream_dessertAsync(ClientOfProject.ServiceReference1.DsetailingScoopOfIceCreamDessert ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDettalingDessertImPurches", ReplyAction="http://tempuri.org/IService1/AddDettalingDessertImPurchesResponse")]
        System.Threading.Tasks.Task<int> AddDettalingDessertImPurchesAsync(ClientOfProject.ServiceReference1.DetailingDessertInPurchase d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DellAdditionAcordingCategory", ReplyAction="http://tempuri.org/IService1/DellAdditionAcordingCategoryResponse")]
        System.Threading.Tasks.Task DellAdditionAcordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DellAdditions", ReplyAction="http://tempuri.org/IService1/DellAdditionsResponse")]
        System.Threading.Tasks.Task DellAdditionsAsync(ClientOfProject.ServiceReference1.Additions a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DellFlavorIceCream", ReplyAction="http://tempuri.org/IService1/DellFlavorIceCreamResponse")]
        System.Threading.Tasks.Task DellFlavorIceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DellSpecialDessert", ReplyAction="http://tempuri.org/IService1/DellSpecialDessertResponse")]
        System.Threading.Tasks.Task DellSpecialDessertAsync(ClientOfProject.ServiceReference1.SpecialDessert s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateAdditionAccordingCategory", ReplyAction="http://tempuri.org/IService1/UpDateAdditionAccordingCategoryResponse")]
        System.Threading.Tasks.Task UpDateAdditionAccordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateAdditions", ReplyAction="http://tempuri.org/IService1/UpDateAdditionsResponse")]
        System.Threading.Tasks.Task UpDateAdditionsAsync(ClientOfProject.ServiceReference1.Additions a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateClients", ReplyAction="http://tempuri.org/IService1/UpDateClientsResponse")]
        System.Threading.Tasks.Task UpDateClientsAsync(ClientOfProject.ServiceReference1.Clients c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateConstantConstricted", ReplyAction="http://tempuri.org/IService1/UpDateConstantConstrictedResponse")]
        System.Threading.Tasks.Task UpDateConstantConstrictedAsync(ClientOfProject.ServiceReference1.ConstantConstricted con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateConstrictedIinPurchase", ReplyAction="http://tempuri.org/IService1/UpDateConstrictedIinPurchaseResponse")]
        System.Threading.Tasks.Task UpDateConstrictedIinPurchaseAsync(ClientOfProject.ServiceReference1.ConstrictedIinPurchase copu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateDsetailingScoopOfIceCreamDessert", ReplyAction="http://tempuri.org/IService1/UpDateDsetailingScoopOfIceCreamDessertResponse")]
        System.Threading.Tasks.Task UpDateDsetailingScoopOfIceCreamDessertAsync(ClientOfProject.ServiceReference1.DsetailingScoopOfIceCreamDessert dscoop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateDetailingDessertInPurchase", ReplyAction="http://tempuri.org/IService1/UpDateDetailingDessertInPurchaseResponse")]
        System.Threading.Tasks.Task UpDateDetailingDessertInPurchaseAsync(ClientOfProject.ServiceReference1.DetailingDessertInPurchase dtdessert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateFlavorsIiceCream", ReplyAction="http://tempuri.org/IService1/UpDateFlavorsIiceCreamResponse")]
        System.Threading.Tasks.Task UpDateFlavorsIiceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDatePurchases", ReplyAction="http://tempuri.org/IService1/UpDatePurchasesResponse")]
        System.Threading.Tasks.Task UpDatePurchasesAsync(ClientOfProject.ServiceReference1.Purchases p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateSpecialDessert", ReplyAction="http://tempuri.org/IService1/UpDateSpecialDessertResponse")]
        System.Threading.Tasks.Task UpDateSpecialDessertAsync(ClientOfProject.ServiceReference1.SpecialDessert sp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientOfProject.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientOfProject.ServiceReference1.IService1>, ClientOfProject.ServiceReference1.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.FlavorsIiceCream>> GetAllFlavorsAsync() {
            return base.Channel.GetAllFlavorsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.SpecialDessert>> GetSpecielDessertAsync() {
            return base.Channel.GetSpecielDessertAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.AdditionAccordingCategory>> GetAllAdditionsAsync(ClientOfProject.ServiceReference1.Category c) {
            return base.Channel.GetAllAdditionsAsync(c);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.Additions>> GetAdditionsAsync() {
            return base.Channel.GetAdditionsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.Category>> GetAllCategoryAsync() {
            return base.Channel.GetAllCategoryAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.SpecificationAdditionsDessert>> GetSpecificationAdditionsDessertsAsync() {
            return base.Channel.GetSpecificationAdditionsDessertsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientOfProject.ServiceReference1.AdditionAccordingCategory>> GetAdditionAccordingCategoriesAsync() {
            return base.Channel.GetAdditionAccordingCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToAdditionAsync() {
            return base.Channel.GetCodeToAdditionAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToFlavorsAsync() {
            return base.Channel.GetCodeToFlavorsAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToMutzarAsync() {
            return base.Channel.GetCodeToMutzarAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToClientAsync() {
            return base.Channel.GetCodeToClientAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToDettalingDessertAsync() {
            return base.Channel.GetCodeToDettalingDessertAsync();
        }
        
        public System.Threading.Tasks.Task AddAdditionAcordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad) {
            return base.Channel.AddAdditionAcordingCategoryAsync(ad);
        }
        
        public System.Threading.Tasks.Task<int> AddAditionAsync(ClientOfProject.ServiceReference1.Additions a) {
            return base.Channel.AddAditionAsync(a);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(ClientOfProject.ServiceReference1.Clients c) {
            return base.Channel.AddClientAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddspecialdessertAsync(ClientOfProject.ServiceReference1.SpecialDessert s) {
            return base.Channel.AddspecialdessertAsync(s);
        }
        
        public System.Threading.Tasks.Task<int> AddConstantConstrictedAsync(ClientOfProject.ServiceReference1.ConstantConstricted con) {
            return base.Channel.AddConstantConstrictedAsync(con);
        }
        
        public System.Threading.Tasks.Task<int> AddFlavorIceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla) {
            return base.Channel.AddFlavorIceCreamAsync(fla);
        }
        
        public System.Threading.Tasks.Task<int> AddPurchesAsync(ClientOfProject.ServiceReference1.Purchases pr) {
            return base.Channel.AddPurchesAsync(pr);
        }
        
        public System.Threading.Tasks.Task<int> AddSpecificationAdditionsDessertAsync(ClientOfProject.ServiceReference1.SpecificationAdditionsDessert sad) {
            return base.Channel.AddSpecificationAdditionsDessertAsync(sad);
        }
        
        public System.Threading.Tasks.Task<int> Adddetailing_scoop_of_ice_cream_dessertAsync(ClientOfProject.ServiceReference1.DsetailingScoopOfIceCreamDessert ds) {
            return base.Channel.Adddetailing_scoop_of_ice_cream_dessertAsync(ds);
        }
        
        public System.Threading.Tasks.Task<int> AddDettalingDessertImPurchesAsync(ClientOfProject.ServiceReference1.DetailingDessertInPurchase d) {
            return base.Channel.AddDettalingDessertImPurchesAsync(d);
        }
        
        public System.Threading.Tasks.Task DellAdditionAcordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad) {
            return base.Channel.DellAdditionAcordingCategoryAsync(ad);
        }
        
        public System.Threading.Tasks.Task DellAdditionsAsync(ClientOfProject.ServiceReference1.Additions a) {
            return base.Channel.DellAdditionsAsync(a);
        }
        
        public System.Threading.Tasks.Task DellFlavorIceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla) {
            return base.Channel.DellFlavorIceCreamAsync(fla);
        }
        
        public System.Threading.Tasks.Task DellSpecialDessertAsync(ClientOfProject.ServiceReference1.SpecialDessert s) {
            return base.Channel.DellSpecialDessertAsync(s);
        }
        
        public System.Threading.Tasks.Task UpDateAdditionAccordingCategoryAsync(ClientOfProject.ServiceReference1.AdditionAccordingCategory ad) {
            return base.Channel.UpDateAdditionAccordingCategoryAsync(ad);
        }
        
        public System.Threading.Tasks.Task UpDateAdditionsAsync(ClientOfProject.ServiceReference1.Additions a) {
            return base.Channel.UpDateAdditionsAsync(a);
        }
        
        public System.Threading.Tasks.Task UpDateClientsAsync(ClientOfProject.ServiceReference1.Clients c) {
            return base.Channel.UpDateClientsAsync(c);
        }
        
        public System.Threading.Tasks.Task UpDateConstantConstrictedAsync(ClientOfProject.ServiceReference1.ConstantConstricted con) {
            return base.Channel.UpDateConstantConstrictedAsync(con);
        }
        
        public System.Threading.Tasks.Task UpDateConstrictedIinPurchaseAsync(ClientOfProject.ServiceReference1.ConstrictedIinPurchase copu) {
            return base.Channel.UpDateConstrictedIinPurchaseAsync(copu);
        }
        
        public System.Threading.Tasks.Task UpDateDsetailingScoopOfIceCreamDessertAsync(ClientOfProject.ServiceReference1.DsetailingScoopOfIceCreamDessert dscoop) {
            return base.Channel.UpDateDsetailingScoopOfIceCreamDessertAsync(dscoop);
        }
        
        public System.Threading.Tasks.Task UpDateDetailingDessertInPurchaseAsync(ClientOfProject.ServiceReference1.DetailingDessertInPurchase dtdessert) {
            return base.Channel.UpDateDetailingDessertInPurchaseAsync(dtdessert);
        }
        
        public System.Threading.Tasks.Task UpDateFlavorsIiceCreamAsync(ClientOfProject.ServiceReference1.FlavorsIiceCream fla) {
            return base.Channel.UpDateFlavorsIiceCreamAsync(fla);
        }
        
        public System.Threading.Tasks.Task UpDatePurchasesAsync(ClientOfProject.ServiceReference1.Purchases p) {
            return base.Channel.UpDatePurchasesAsync(p);
        }
        
        public System.Threading.Tasks.Task UpDateSpecialDessertAsync(ClientOfProject.ServiceReference1.SpecialDessert sp) {
            return base.Channel.UpDateSpecialDessertAsync(sp);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfOfProject/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
